apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-02-deployment
  labels:
    app: lab-02
spec:
  selector:
    matchLabels:
      app: lab-02
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: lab-02
    spec:
      containers:
      - name: app
        image: dauphu80kg/lab-01:2023
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: '/tmp'
            name: demo
      volumes:
        - name: demo
          persistentVolumeClaim:
            claimName: pvc-sample