apiVersion: v1
kind: Service
metadata:
  name: lab-02-service
spec:
  selector:
    app: lab-02
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer